# Go cross compiler (xgo): Wildcard layer to the latest 1.13 release
# Copyright (c) 2014 Péter Szilágyi. All rights reserved.
#
# Released under the MIT license.

FROM karalabe/xgo-1.13.12

MAINTAINER Péter Szilágyi <peterke@gmail.com>
